codessentials/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('posts.urls', namespace='posts')),
)

posts/urls.py
from django.conf.urls import patterns, include, url
from posts.views import *

urlpatterns = patterns('posts.views',
    url(r'^$', 'index', name='index'),
    url(r'^(?P<lang>\w+)/(?P<cat>\w)/(?P<mode>\w)/$', 'get', name='get'),
    url(r'^u/(?P<id>\d+)/$', 'upvote', name='upvote'),
    url(r'^s/$', 'submit', name='submit'),
)

posts/models.py
from django.db import models

from urlparse import urlparse

class Language(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

CAT_CHOICES = (
    ("t", "Text"),
    ("v", "Video"),
    ("b", "Book"),
)

class Post(models.Model):
    name = models.CharField(max_length=140)
    link = models.URLField(unique=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    lang = models.ForeignKey('Language')
    votes = models.IntegerField(default=0)
    cat = models.CharField(max_length=1, choices=CAT_CHOICES)

    def __unicode__(self):
        return self.name

    def slug(self):
        return urlparse(self.link).hostname

posts/forms.py
from django.forms import ModelForm
from posts.models import Post, Language

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['name', 'link', 'lang', 'cat']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['lang'].label = "Language"
        self.fields['lang'].queryset = Language.objects.all().order_by('name')
        self.fields['cat'].label = "Type"

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.utils import timezone
from django.contrib import messages

from posts.models import Language, Post
from posts.forms import PostForm

from datetime import timedelta

"""
Categories:
t - text
v - video
b - book

Modes:
t - top
n - new
d - day
w - week
m - month
"""

def index(request):
    langs = Language.objects.all().order_by('name')
    return render(request, 'index.html', {'langs': langs})

def get(request, lang, cat, mode):
    if cat not in "tvb" or mode not in "tndwm" or not lang:
        return redirect('posts:index')
    posts = Post.objects.filter(lang__name=lang)
    if cat:
        posts = posts.filter(cat=cat)
    if mode == "t":
        posts = posts.order_by('-votes')
    if mode == "n":
        posts = posts.order_by('-pub_date')
    if mode == "d":
        posts = posts.filter(pub_date__gte=timezone.now() - timedelta(days=1)
                            ).order_by('-votes')
    if mode == "w":
        posts = posts.filter(pub_date__gte=timezone.now() - timedelta(days=7)
                            ).order_by('-votes')
    if mode == "m":
        posts = posts.filter(pub_date__gte=timezone.now() - timedelta(days=30)
                            ).order_by('-votes')
    page = request.GET.get('p')
    paginator = Paginator(posts, 25)
    try:
        postlist = paginator.page(page)
    except PageNotAnInteger:
        postlist = paginator.page(1)
    except EmptyPage:
        postlist = paginator.page(paginator.num_pages)
    voted = []
    for post in postlist:
        if str(post.pk) in request.COOKIES:
            voted.append(post.pk)
    context = {'posts': postlist, 'voted': voted, 'cat': cat, 'lang': lang,
               'mode': mode}
    return render(request, 'list.html', context)

def upvote(request, id):
    response = HttpResponse()
    if request.is_ajax() and id not in request.COOKIES:
        response.set_cookie(key=id, value=1)
        post = get_object_or_404(Post, pk=id)
        post.votes += 1
        post.save()
    return response

def submit(request):
    if request.method == 'POST':
        post = Post()
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            p = form.save()
            messages.success(request, "Submission successful!")
            return redirect('posts:index')
    else:
        form = PostForm()
    return render(request, 'submit.html', {'form': form})

templates/index.html
{% extends 'skeleton.html' %}

{% block 'menu' %}
&gt;
<li class="menu"><a href="{% url 'posts:submit' %}">submit</a></li>
{% endblock %}

{% block 'content' %}
{% for lang in langs %}
<li>
<a href="{% url 'posts:get' lang 't' 't'%}" title="{{ lang|capfirst }}">{{ lang|capfirst }}</a>
</li>
{% endfor %}
{% endblock %}

templates/list.html
{% extends 'skeleton.html' %}

{% block 'title' %}
    {% if mode == 't' %}Best
        {% elif mode == 'n' %}Newest
        {% endif %}
    {{ lang|capfirst }}
    {% if cat == 't' %}Text
        {% elif cat == 'v' %}Video
        {% elif cat == 'b'%}Book
        {% endif %}
    Links -
{% endblock %}

{% block 'head' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
{% endblock %}

{% block 'menu' %}
&gt;
<li class="menu"><a {% if mode == 't' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang cat 't' %}">top</a></li>
<li class="menu"><a {% if mode == 'n' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang cat 'n' %}">new</a></li>
<li class="menu"><a {% if mode == 'd' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang cat 'd' %}">day</a></li>
<li class="menu"><a {% if mode == 'w' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang cat 'w' %}">week</a></li>
<li class="menu"><a {% if mode == 'm' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang cat 'm' %}">month</a></li>
&gt;
<li class="menu"><a {% if cat == 't' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang 't' mode %}">text</a></li>
<li class="menu"><a {% if cat == 'v' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang 'v' mode %}">video</a></li>
<li class="menu"><a {% if cat == 'b' %}class="hilight" {% endif %}
href="{% url 'posts:get' lang 'b' mode %}">book</a></li>
&gt;
<li class="menu"><a href="{% url 'posts:submit' %}">submit</a></li>
{% endblock %}

{% block 'content' %}
{% for post in posts %}
<li>
<div>
{% if post.pk not in voted %}
    <a class="vote" href="{% url 'posts:upvote' post.pk %}">+</a>
{% endif %}
<a href="{{ post.link }}" title="{{ post.link }}">{{ post }}</a><br />
<span>{{ post.votes }}</span> Votes |
{{ post.pub_date|date:"Y-m-d" }} |
{{ post.slug }}
</div>
</li>
{% empty %}
<div id="empty">
There seems to be nothing here. Why don't you <a href="{% url 'posts:submit' %}">post something</a>?
</div>
{% endfor %}
<div id="pagination">
    {% if posts.has_previous %}
        <a href="?p={{ posts.previous_page_number }}">&lt;</a>
    {% endif %}

        {{ posts.number }} / {{ posts.paginator.num_pages }}

    {% if posts.has_next %}
        <a href="?p={{ posts.next_page_number }}">&gt;</a>
    {% endif %}
</div>
<script type="text/javascript">
$("a.vote").click(function(){
    var curr = $(this);
    $.get($(this).attr('href'), function(data){
        var ctr = $(curr).parent().children("span");
        ctr.text(ctr.text()*1+1);
        curr.remove();
    });
    return false;
});
</script>
{% endblock %}

templates/skeleton.html
{% load staticfiles %}
<html>
<head>
    <title>{% block 'title' %}{% endblock %}Codessentials</title>
    <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css" />
    {% block 'head' %}
    {% endblock %}
</head>
<body>
    <div id="container">
    <div id="top">
        <a id="logo" href="/">Codessentials</a>
        {% block 'menu' %}
        {% endblock %}
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="messages msg_{{ message.level }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div id="ad_banner">
    <!-- Adsense -->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <ins class="adsbygoogle"
    style="display:inline-block;width:728px;height:90px"
    data-ad-client="ca-pub-5757275602398953"
    data-ad-slot="2887394551"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
    </div>
    <!-- Analytics -->
    <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-38330260-6', 'auto');
    ga('send', 'pageview');

    </script>
    {% block 'content' %}
    {% endblock %}
    </div>
</body>
</html>

templates/submit.html
{% extends 'skeleton.html' %}

{% block 'title' %}
Post a new link
{% endblock %}

{% block 'content' %}
<form action="." method="POST">
{% csrf_token %}
<table>
{{ form.as_table }}
<tr><td></td><td><input type="submit" value="Save" /></td></tr>
</table>
</form>
{% endblock %}